#ifndef SECURE_SERVERLESS_COMMON_CRYPTCONST_H_
#define SECURE_SERVERLESS_COMMON_CRYPTCONST_H_

#define AES_GCM_IV_SIZE 12
#define AES_GCM_TAG_SIZE 16
#define AES_GCM_AAD_SIZE 4

#endif  // SECURE_SERVERLESS_COMMON_CRYPTCONST_H_
